// Auto-generated unit macro with human-readable triangular structure
// Generated by generate_unit_macros_clean.rs
// 
// This macro provides LSP-friendly declarative patterns for common unit expressions.
// For complex expressions not covered here, use proc_unit!() instead.

#[macro_export]
macro_rules! define_unit_macro {
    (
        $mass_unused:expr,
        $length_unused:expr,
        $time_unused_p2:expr, $time_unused_p3:expr, $time_unused_p5:expr
    ) => {
        macro_rules! unit {
            // ============================================================================
            // SINGLE UNITS (Base units)
            // ============================================================================
            // Mass units
            (mg) => { crate::Quantity<
                        1, -6,
                        0, $length_unused,
                        0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                    > };
            (g) => { crate::Quantity<
                        1, -3,
                        0, $length_unused,
                        0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                    > };
            (kg) => { crate::Quantity<
                        1, 0,
                        0, $length_unused,
                        0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                    > };
            // Length units
            (mm) => { crate::Quantity<
                        0, $mass_unused,
                        1, -3,
                        0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                    > };
            (m) => { crate::Quantity<
                        0, $mass_unused,
                        1, 0,
                        0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                    > };
            (km) => { crate::Quantity<
                        0, $mass_unused,
                        1, 3,
                        0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                    > };
            // Time units
            (ms) => { crate::Quantity<
                        0, $mass_unused,
                        0, $length_unused,
                        1, -3, 0, -3
                    > };
            (s) => { crate::Quantity<
                        0, $mass_unused,
                        0, $length_unused,
                        1, 0, 0, 0
                    > };
            (min) => { crate::Quantity<
                        0, $mass_unused,
                        0, $length_unused,
                        1, 2, 1, 1
                    > };

            // ============================================================================
            // UNITS WITH EXPONENTS (Squared, cubed, etc.)
            // ============================================================================
            // Mass units with dynamic exponents
            (mg^$exp:tt) => { crate::Quantity<
                            $exp, -6,
                            0, $length_unused,
                            0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                        > };
            (g^$exp:tt) => { crate::Quantity<
                            $exp, -3,
                            0, $length_unused,
                            0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                        > };
            (kg^$exp:tt) => { crate::Quantity<
                            $exp, 0,
                            0, $length_unused,
                            0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                        > };
            // Length units with dynamic exponents
            (mm^$exp:tt) => { crate::Quantity<
                            0, $mass_unused,
                            $exp, -3,
                            0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                        > };
            (m^$exp:tt) => { crate::Quantity<
                            0, $mass_unused,
                            $exp, 0,
                            0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                        > };
            (km^$exp:tt) => { crate::Quantity<
                            0, $mass_unused,
                            $exp, 3,
                            0, $time_unused_p2, $time_unused_p3, $time_unused_p5
                        > };
            // Time units with dynamic exponents
            (ms^$exp:tt) => { crate::Quantity<
                            0, $mass_unused,
                            0, $length_unused,
                            $exp, -3, 0, -3
                        > };
            (s^$exp:tt) => { crate::Quantity<
                            0, $mass_unused,
                            0, $length_unused,
                            $exp, 0, 0, 0
                        > };
            (min^$exp:tt) => { crate::Quantity<
                            0, $mass_unused,
                            0, $length_unused,
                            $exp, 2, 1, 1
                        > };

            // ============================================================================
            // COMPOUND UNITS (Two units multiplied)
            // ============================================================================
            // Mass × Mass
            (mg * mg) => { crate::Quantity<
                2, -6,
                0, $length_unused,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (g * mg) => { crate::Quantity<
                2, -3,
                0, $length_unused,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (g * g) => { crate::Quantity<
                2, -3,
                0, $length_unused,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (kg * mg) => { crate::Quantity<
                2, 0,
                0, $length_unused,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (kg * g) => { crate::Quantity<
                2, 0,
                0, $length_unused,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (kg * kg) => { crate::Quantity<
                2, 0,
                0, $length_unused,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            // Length × Length
            (mm * mm) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (m * mm) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (m * m) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (km * mm) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (km * m) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (km * km) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            // Mass × Length
            (mg * mm) => { crate::Quantity<
                1, -6,
                1, -3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (mg * m) => { crate::Quantity<
                1, -6,
                1, 0,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (mg * km) => { crate::Quantity<
                1, -6,
                1, 3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (g * mm) => { crate::Quantity<
                1, -3,
                1, -3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (g * m) => { crate::Quantity<
                1, -3,
                1, 0,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (g * km) => { crate::Quantity<
                1, -3,
                1, 3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (kg * mm) => { crate::Quantity<
                1, 0,
                1, -3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (kg * m) => { crate::Quantity<
                1, 0,
                1, 0,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            (kg * km) => { crate::Quantity<
                1, 0,
                1, 3,
                0, $time_unused_p2, $time_unused_p3, $time_unused_p5
            > };
            // Mass × Time
            (mg * ms) => { crate::Quantity<
                1, -6,
                0, $mass_unused,
                1, -3, 0, -3
            > };
            (mg * s) => { crate::Quantity<
                1, -6,
                0, $mass_unused,
                1, 0, 0, 0
            > };
            (mg * min) => { crate::Quantity<
                1, -6,
                0, $mass_unused,
                1, 2, 1, 1
            > };
            (g * ms) => { crate::Quantity<
                1, -3,
                0, $mass_unused,
                1, -3, 0, -3
            > };
            (g * s) => { crate::Quantity<
                1, -3,
                0, $mass_unused,
                1, 0, 0, 0
            > };
            (g * min) => { crate::Quantity<
                1, -3,
                0, $mass_unused,
                1, 2, 1, 1
            > };
            (kg * ms) => { crate::Quantity<
                1, 0,
                0, $mass_unused,
                1, -3, 0, -3
            > };
            (kg * s) => { crate::Quantity<
                1, 0,
                0, $mass_unused,
                1, 0, 0, 0
            > };
            (kg * min) => { crate::Quantity<
                1, 0,
                0, $mass_unused,
                1, 2, 1, 1
            > };
            // Length × Time
            (mm * ms) => { crate::Quantity<
                0, $mass_unused,
                1, -3,
                1, -3, 0, -3
            > };
            (mm * s) => { crate::Quantity<
                0, $mass_unused,
                1, -3,
                1, 0, 0, 0
            > };
            (mm * min) => { crate::Quantity<
                0, $mass_unused,
                1, -3,
                1, 2, 1, 1
            > };
            (m * ms) => { crate::Quantity<
                0, $mass_unused,
                1, 0,
                1, -3, 0, -3
            > };
            (m * s) => { crate::Quantity<
                0, $mass_unused,
                1, 0,
                1, 0, 0, 0
            > };
            (m * min) => { crate::Quantity<
                0, $mass_unused,
                1, 0,
                1, 2, 1, 1
            > };
            (km * ms) => { crate::Quantity<
                0, $mass_unused,
                1, 3,
                1, -3, 0, -3
            > };
            (km * s) => { crate::Quantity<
                0, $mass_unused,
                1, 3,
                1, 0, 0, 0
            > };
            (km * min) => { crate::Quantity<
                0, $mass_unused,
                1, 3,
                1, 2, 1, 1
            > };

            // ============================================================================
            // VELOCITY UNITS (Length / Time)
            // ============================================================================
            (mm / ms) => { crate::Quantity<
                0, $mass_unused,
                1, -3,
                -1, -3, 0, -3
            > };
            (mm / s) => { crate::Quantity<
                0, $mass_unused,
                1, -3,
                -1, 0, 0, 0
            > };
            (mm / min) => { crate::Quantity<
                0, $mass_unused,
                1, -3,
                -1, 2, 1, 1
            > };
            (m / ms) => { crate::Quantity<
                0, $mass_unused,
                1, 0,
                -1, -3, 0, -3
            > };
            (m / s) => { crate::Quantity<
                0, $mass_unused,
                1, 0,
                -1, 0, 0, 0
            > };
            (m / min) => { crate::Quantity<
                0, $mass_unused,
                1, 0,
                -1, 2, 1, 1
            > };
            (km / ms) => { crate::Quantity<
                0, $mass_unused,
                1, 3,
                -1, -3, 0, -3
            > };
            (km / s) => { crate::Quantity<
                0, $mass_unused,
                1, 3,
                -1, 0, 0, 0
            > };
            (km / min) => { crate::Quantity<
                0, $mass_unused,
                1, 3,
                -1, 2, 1, 1
            > };

            // ============================================================================
            // ACCELERATION UNITS (Length / Time²)
            // ============================================================================
            (mm / ms^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, -3,
                -$exp, -3, 0, -3
            > };
            (mm / s^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, -3,
                -$exp, 0, 0, 0
            > };
            (mm / min^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, -3,
                -$exp, 2, 1, 1
            > };
            (m / ms^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, 0,
                -$exp, -3, 0, -3
            > };
            (m / s^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, 0,
                -$exp, 0, 0, 0
            > };
            (m / min^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, 0,
                -$exp, 2, 1, 1
            > };
            (km / ms^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, 3,
                -$exp, -3, 0, -3
            > };
            (km / s^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, 3,
                -$exp, 0, 0, 0
            > };
            (km / min^$exp:tt) => { crate::Quantity<
                0, $mass_unused,
                $exp, 3,
                -$exp, 2, 1, 1
            > };

            // ============================================================================
            // FORCE UNITS (Mass × Length / Time²)
            // ============================================================================
            (mg * mm / ms^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, -3,
                -$exp, -3, 0, -3
            > };
            (mg * mm / s^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, -3,
                -$exp, 0, 0, 0
            > };
            (mg * mm / min^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, -3,
                -$exp, 2, 1, 1
            > };
            (mg * m / ms^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, 0,
                -$exp, -3, 0, -3
            > };
            (mg * m / s^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, 0,
                -$exp, 0, 0, 0
            > };
            (mg * m / min^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, 0,
                -$exp, 2, 1, 1
            > };
            (mg * km / ms^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, 3,
                -$exp, -3, 0, -3
            > };
            (mg * km / s^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, 3,
                -$exp, 0, 0, 0
            > };
            (mg * km / min^$exp:tt) => { crate::Quantity<
                $exp, -6,
                $exp, 3,
                -$exp, 2, 1, 1
            > };
            (g * mm / ms^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, -3,
                -$exp, -3, 0, -3
            > };
            (g * mm / s^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, -3,
                -$exp, 0, 0, 0
            > };
            (g * mm / min^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, -3,
                -$exp, 2, 1, 1
            > };
            (g * m / ms^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, 0,
                -$exp, -3, 0, -3
            > };
            (g * m / s^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, 0,
                -$exp, 0, 0, 0
            > };
            (g * m / min^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, 0,
                -$exp, 2, 1, 1
            > };
            (g * km / ms^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, 3,
                -$exp, -3, 0, -3
            > };
            (g * km / s^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, 3,
                -$exp, 0, 0, 0
            > };
            (g * km / min^$exp:tt) => { crate::Quantity<
                $exp, -3,
                $exp, 3,
                -$exp, 2, 1, 1
            > };
            (kg * mm / ms^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, -3,
                -$exp, -3, 0, -3
            > };
            (kg * mm / s^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, -3,
                -$exp, 0, 0, 0
            > };
            (kg * mm / min^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, -3,
                -$exp, 2, 1, 1
            > };
            (kg * m / ms^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, 0,
                -$exp, -3, 0, -3
            > };
            (kg * m / s^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, 0,
                -$exp, 0, 0, 0
            > };
            (kg * m / min^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, 0,
                -$exp, 2, 1, 1
            > };
            (kg * km / ms^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, 3,
                -$exp, -3, 0, -3
            > };
            (kg * km / s^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, 3,
                -$exp, 0, 0, 0
            > };
            (kg * km / min^$exp:tt) => { crate::Quantity<
                $exp, 0,
                $exp, 3,
                -$exp, 2, 1, 1
            > };

            // ============================================================================
            // ENERGY UNITS (Mass × Length² / Time²)
            // ============================================================================
            (mg * mm^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, -3,
                -$exp2, -3, 0, -3
            > };
            (mg * mm^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, -3,
                -$exp2, 0, 0, 0
            > };
            (mg * mm^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, -3,
                -$exp2, 2, 1, 1
            > };
            (mg * m^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 0,
                -$exp2, -3, 0, -3
            > };
            (mg * m^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 0,
                -$exp2, 0, 0, 0
            > };
            (mg * m^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 0,
                -$exp2, 2, 1, 1
            > };
            (mg * km^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 3,
                -$exp2, -3, 0, -3
            > };
            (mg * km^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 3,
                -$exp2, 0, 0, 0
            > };
            (mg * km^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 3,
                -$exp2, 2, 1, 1
            > };
            (g * mm^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, -3,
                -$exp2, -3, 0, -3
            > };
            (g * mm^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, -3,
                -$exp2, 0, 0, 0
            > };
            (g * mm^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, -3,
                -$exp2, 2, 1, 1
            > };
            (g * m^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 0,
                -$exp2, -3, 0, -3
            > };
            (g * m^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 0,
                -$exp2, 0, 0, 0
            > };
            (g * m^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 0,
                -$exp2, 2, 1, 1
            > };
            (g * km^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 3,
                -$exp2, -3, 0, -3
            > };
            (g * km^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 3,
                -$exp2, 0, 0, 0
            > };
            (g * km^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 3,
                -$exp2, 2, 1, 1
            > };
            (kg * mm^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, -3,
                -$exp2, -3, 0, -3
            > };
            (kg * mm^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, -3,
                -$exp2, 0, 0, 0
            > };
            (kg * mm^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, -3,
                -$exp2, 2, 1, 1
            > };
            (kg * m^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 0,
                -$exp2, -3, 0, -3
            > };
            (kg * m^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 0,
                -$exp2, 0, 0, 0
            > };
            (kg * m^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 0,
                -$exp2, 2, 1, 1
            > };
            (kg * km^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 3,
                -$exp2, -3, 0, -3
            > };
            (kg * km^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 3,
                -$exp2, 0, 0, 0
            > };
            (kg * km^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 3,
                -$exp2, 2, 1, 1
            > };

            // ============================================================================
            // POWER UNITS (Mass × Length² / Time³)
            // ============================================================================
            (mg * mm^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, -3,
                -$exp2, -3, 0, -3
            > };
            (mg * mm^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, -3,
                -$exp2, 0, 0, 0
            > };
            (mg * mm^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, -3,
                -$exp2, 2, 1, 1
            > };
            (mg * m^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 0,
                -$exp2, -3, 0, -3
            > };
            (mg * m^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 0,
                -$exp2, 0, 0, 0
            > };
            (mg * m^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 0,
                -$exp2, 2, 1, 1
            > };
            (mg * km^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 3,
                -$exp2, -3, 0, -3
            > };
            (mg * km^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 3,
                -$exp2, 0, 0, 0
            > };
            (mg * km^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -6,
                $exp1, 3,
                -$exp2, 2, 1, 1
            > };
            (g * mm^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, -3,
                -$exp2, -3, 0, -3
            > };
            (g * mm^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, -3,
                -$exp2, 0, 0, 0
            > };
            (g * mm^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, -3,
                -$exp2, 2, 1, 1
            > };
            (g * m^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 0,
                -$exp2, -3, 0, -3
            > };
            (g * m^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 0,
                -$exp2, 0, 0, 0
            > };
            (g * m^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 0,
                -$exp2, 2, 1, 1
            > };
            (g * km^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 3,
                -$exp2, -3, 0, -3
            > };
            (g * km^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 3,
                -$exp2, 0, 0, 0
            > };
            (g * km^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, -3,
                $exp1, 3,
                -$exp2, 2, 1, 1
            > };
            (kg * mm^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, -3,
                -$exp2, -3, 0, -3
            > };
            (kg * mm^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, -3,
                -$exp2, 0, 0, 0
            > };
            (kg * mm^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, -3,
                -$exp2, 2, 1, 1
            > };
            (kg * m^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 0,
                -$exp2, -3, 0, -3
            > };
            (kg * m^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 0,
                -$exp2, 0, 0, 0
            > };
            (kg * m^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 0,
                -$exp2, 2, 1, 1
            > };
            (kg * km^$exp1:tt / ms^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 3,
                -$exp2, -3, 0, -3
            > };
            (kg * km^$exp1:tt / s^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 3,
                -$exp2, 0, 0, 0
            > };
            (kg * km^$exp1:tt / min^$exp2:tt) => { crate::Quantity<
                $exp1, 0,
                $exp1, 3,
                -$exp2, 2, 1, 1
            > };

            // ============================================================================
            // COMPLEX COMPOUND UNITS
            // ============================================================================
            (mm * mm / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, -3, 0, -3
            > };
            (mm * mm / s) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 0, 0, 0
            > };
            (mm * mm / min) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 2, 1, 1
            > };
            (mm * m / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, -3, 0, -3
            > };
            (mm * m / s) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 0, 0, 0
            > };
            (mm * m / min) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 2, 1, 1
            > };
            (mm * km / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, -3, 0, -3
            > };
            (mm * km / s) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 0, 0, 0
            > };
            (mm * km / min) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 2, 1, 1
            > };
            (m * mm / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, -3, 0, -3
            > };
            (m * mm / s) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 0, 0, 0
            > };
            (m * mm / min) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 2, 1, 1
            > };
            (m * m / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, -3, 0, -3
            > };
            (m * m / s) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 0, 0, 0
            > };
            (m * m / min) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 2, 1, 1
            > };
            (m * km / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, -3, 0, -3
            > };
            (m * km / s) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 0, 0, 0
            > };
            (m * km / min) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 2, 1, 1
            > };
            (km * mm / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, -3, 0, -3
            > };
            (km * mm / s) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, 0, 0, 0
            > };
            (km * mm / min) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, 2, 1, 1
            > };
            (km * m / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, -3, 0, -3
            > };
            (km * m / s) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, 0, 0, 0
            > };
            (km * m / min) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, 2, 1, 1
            > };
            (km * km / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, -3, 0, -3
            > };
            (km * km / s) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, 0, 0, 0
            > };
            (km * km / min) => { crate::Quantity<
                0, $mass_unused,
                2, 3,
                -1, 2, 1, 1
            > };
            (mg * mg / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, -3, 0, -3
            > };
            (mg * mg / s) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, 0, 0, 0
            > };
            (mg * mg / min) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, 2, 1, 1
            > };
            (mg * g / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, -3, 0, -3
            > };
            (mg * g / s) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, 0, 0, 0
            > };
            (mg * g / min) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, 2, 1, 1
            > };
            (mg * kg / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, -3, 0, -3
            > };
            (mg * kg / s) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, 0, 0, 0
            > };
            (mg * kg / min) => { crate::Quantity<
                0, $mass_unused,
                2, -6,
                -1, 2, 1, 1
            > };
            (g * mg / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, -3, 0, -3
            > };
            (g * mg / s) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 0, 0, 0
            > };
            (g * mg / min) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 2, 1, 1
            > };
            (g * g / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, -3, 0, -3
            > };
            (g * g / s) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 0, 0, 0
            > };
            (g * g / min) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 2, 1, 1
            > };
            (g * kg / ms) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, -3, 0, -3
            > };
            (g * kg / s) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 0, 0, 0
            > };
            (g * kg / min) => { crate::Quantity<
                0, $mass_unused,
                2, -3,
                -1, 2, 1, 1
            > };
            (kg * mg / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, -3, 0, -3
            > };
            (kg * mg / s) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 0, 0, 0
            > };
            (kg * mg / min) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 2, 1, 1
            > };
            (kg * g / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, -3, 0, -3
            > };
            (kg * g / s) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 0, 0, 0
            > };
            (kg * g / min) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 2, 1, 1
            > };
            (kg * kg / ms) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, -3, 0, -3
            > };
            (kg * kg / s) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 0, 0, 0
            > };
            (kg * kg / min) => { crate::Quantity<
                0, $mass_unused,
                2, 0,
                -1, 2, 1, 1
            > };
            (ms * ms / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * ms / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * ms / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * s / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * s / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * s / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * min / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * min / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (ms * min / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, -3, 0, -3
            > };
            (s * ms / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * ms / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * ms / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * s / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * s / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * s / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * min / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * min / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (s * min / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 0, 0, 0
            > };
            (min * ms / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * ms / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * ms / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * s / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * s / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * s / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * min / ms) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * min / s) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };
            (min * min / min) => { crate::Quantity<
                0, $mass_unused,
                0, $length_unused,
                1, 2, 1, 1
            > };

            // ============================================================================
            // CATCH-ALL FOR UNKNOWN UNITS
            // ============================================================================
            ($unknown:tt) => {
                compile_error!(concat!("Unknown unit: ", stringify!($unknown), ". Use proc_unit!() for complex expressions."))
            };
        }
    };
}

// The unit macro is now only defined through set_unit_preferences!
// This prevents conflicts between global and scoped versions
